config/routes.rb
Rails.application.routes.draw do
  resources :user_projects
  resources :artifacts
  resources :tenants do
    resources :projects, except: [ :index ] do
      get 'users', on: :member
      put 'add_user', on: :member
    end
  end
  resources :members
  get 'home/index'

  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => {
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions => "milia/sessions",
    :passwords => "milia/passwords",
  }

  match 'plan/edit' => 'tenants#edit', via: :get, as: :edit_plan
  match 'plan/update' => 'tenants#update', via: [:patch, :patch], as: :update_plan

  root :to => "home#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_tenant!, :only => [ :index ]

  def index
    if current_user
      if session[:tenant_id]
        Tenant.set_current_tenant session[:tenant_id]
      else
        Tenant.set_current_tenant current_user.tenants.first
      end

      @tenant = Tenant.current_tenant
      @projects = Project.by_user_plan_and_tenant(@tenant.id, current_user)
      params[:tenant_id] = @tenant.id
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_welcome_banner.html.erb
<div class="jumbotron">
    <h1>Welcome to the project management application</h1>
    <p>Need to organize or manage your project? Take a look at our great plans!</p>
</div>


<div class="container">
    <div class="row ">
        <div class="col-md-4 col-md-offset-2">
            <div class="panel panel-success">
                <div class="panel-heading text-center">
                    <h2>Free Plan</h2>
                </div>
                <div class="panel-body">
                    <ul>
                        <li><strong>Price: Free</strong></li>
                        <li>Responsive design</li>
                        <li>Access Anywhere</li>
                        <li>1 Project</li>
                    </ul>
                    <div class="text-center">
                        <%= link_to new_user_registration_path do %>
                            <button type="button" class="btn btn-primary btn-lg mt-2 text-center">Sign up!</button>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="panel panel-primary">
                <div class="panel-heading text-center">
                    <h2>Premium Plan</h2>
                </div>
                <div class="panel-body">
                    <ul>
                        <li><strong>Price: $10</strong></li>
                        <li>Responsive design</li>
                        <li>Access Anywhere</li>
                        <li>Unlimited Projects</li>
                    </ul>
                    <div class="text-center">
                        <%= link_to new_user_registration_path(plan: "premium") do %>
                            <button type="button" class="btn btn-primary btn-lg mt-2 text-center">Sign up!</button>
                        <% end %>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<% if !user_signed_in? %>
    <%= render "welcome_banner" %>
<% else %>

    <h1>
        Organization: <strong> <%= @tenant.name %> </strong>
    </h1>
    <% if @tenant.can_create_projects? %>
        <%= link_to new_tenant_project_path(@tenant.id) do %>
            <button class="btn btn-primary align-center">
                <%= bootstrap_icon "plus-circle" %> New Project
            </button>
        <% end %>
    <% end %>
    <% if @projects.length == 0 %>
        <h2 class="text-center"> You have no projects </h2>
    <% else %>
        <h2>Projects:</h2>
        <div class="row">
            <%= render @projects %>
        <div>
    <% end %>

<% end %>