config/routes.rb
Rails.application.routes.draw do
  resources :user_projects
  resources :artifacts
  resources :tenants do
    resources :projects, except: [ :index ] do
      get 'users', on: :member
      put 'add_user', on: :member
    end
  end
  resources :members
  get 'home/index'

  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => {
    :registrations => "registrations",
    :confirmations => "confirmations",
    :sessions => "milia/sessions",
    :passwords => "milia/passwords",
  }

  match 'plan/edit' => 'tenants#edit', via: :get, as: :edit_plan
  match 'plan/update' => 'tenants#update', via: [:patch, :patch], as: :update_plan

  root :to => "home#index"
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default ">
    <div class="container-fluid margin-x">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <%= link_to root_path, class:"navbar-brand align-center" do %>
                <%= bootstrap_icon("building", width: 30, height: 30) %>
                SaasApp
            <% end %>
        </div>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
            <% if user_signed_in? && current_user.is_admin?%>
            <ul class="nav navbar-nav">
                <li >
                    <%= link_to new_member_path, class:"align-center special-btn" do  %>
                        <%= bootstrap_icon "person-plus"%>
                        Invite a new user
                    <% end %>
                </li>
            </ul>
            <% end %>
            <ul class="nav navbar-nav navbar-right">
                <% if user_signed_in? %>
                    <li role="presentation" class="drop-down">
                        <a class="dropdown-toggle align-center" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            <%= bootstrap_icon "person-circle"%>
                            <%= current_user.email %> <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <%= link_to "Logout",destroy_user_session_path, method: :delete%>
                            </li>
                            <li>
                                <%= link_to "Edit plan", edit_plan_path%>
                            </li>
                        </ul>
                    </li>
                <% else %>
                    <li>
                        <%= link_to new_user_session_path do %>
                            <button type="button" class="btn btn-default">Login</button>
                        <% end %>
                    </li>
                    <li>
                        <%= link_to new_user_registration_path do %>
                            <button type="button" class="btn btn-primary">Sign up</button>
                        <% end %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SaasApp" %></title>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#  favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' > %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#  favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'%>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#  favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'%>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#  favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#  favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
    <%= javascript_include_tag "https://js.stripe.com/v2/"%>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>
    <%= render "layouts/navbar" %>
    <div class="container" id= "main">
      <div class="row">
        <div class="col-lg">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p class= "text-center">&copy; Joaquin Berrios (2022)</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>